name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Körs varje natt
  workflow_dispatch:               # Gör att du kan starta den manuellt
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: angelicagardner
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Stockholm
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes
