name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Stockholm
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugins_errors_fatal: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_leetcode: yes
          plugin_leetcode_user: angelicahjelmgardner
          plugin_leetcode_sections: solved, skills
